apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      valueFiles:
      - $values/envs/k3s/grafana/values.yaml
  - repoURL: 'https://github.com/denisl78/poc'
    targetRevision: dev
    ref: values
  - repoURL: 'https://github.com/denisl78/poc'
    targetRevision: dev
    path: 'argocd/k3s/grafana/'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

